#!/bin/sh
#
# build environment for building MySQL from src.rpms
#

myname=$(basename $0)

log () {
	echo "$(date +'%Y-%m-%d %H:%M:%S') $myname[$$]: $@"
}

exit_error () {
	log "ERROR: $@"
	exit 1
}

get_os_and_version () {
	if [ -z "$ID" ]; then
		. /etc/os-release

		case $ID in
		almalinux|ol|rocky|centos|rhel)
			# convert to a single digit if there's a decimal part
			BUILD_VERSION=$(echo $VERSION_ID | sed -e 's/\..*//')
			;;
		*)
			exit_error "Unrecognised OS: $NAME ($ID $VERSION_ID). Provide a patch to support your linux version if needed."
		esac
	fi
}

setup_build_user () {
	if ! grep $BUILD_USER /etc/passwd; then
		log "### Adding missing build user: $BUILD_USER"
		useradd -m $BUILD_USER
	else
		log "### Required build user $BUILD_USER already present"
	fi

	# Create missing directories used for persisting data
	local directories="/data/SRPMS /data/log /data/built"
	local dir

	for dir in $directories; do
		if ! test -d $dir; then
			log "Creating missing directory: $dir, ownership set to $BUILD_USER:$BUILD_USER"
			mkdir -p $dir
			chown $BUILD_USER:$BUILD_USER $dir
		fi
	done
}

# Install the appropriate src.rpm from upstream sources
# - keep local copy to speed up process so if we do this frequently
install_srpms () {
	local SRPMS="$1" # space separated list of src.rpms to install from urls
	local location
	local rpm
	local url

	log "########################################################"
	log "#                 Installing SRPMS                     #"
	log "########################################################"
	echo
	for url in $SRPMS; do
		log "- Want to install $url"
		rpm=$(basename $url)
		location=/data/SRPMS/$rpm
		if [ -e $location ]; then
			log "- Found cached $location"
		else
			log "- Downloading $url to $location"
			( cd /data/SRPMS && wget $url )
		fi
		log "- Installing $url from $location"
		rpm -ivh $location
	done
	log "- SRPMS installed:"
	ls -l ~/rpmbuild/SOURCES/ ~/rpmbuild/SPECS
	echo
}

# - just copy the file and log
copy_file () {
	local src=$1
	local dst=$2

	log "- copying $src to $dst"
	cp $src $dst
}

copy_files () {
	local srcdir=$1
	local dstdir=$2
	local file

	if [ -d $srcdir ]; then
		for file in $srcdir/*; do
			copy_file $file $dstdir/
		done
	fi
}

# install custom patches / sources for the specified build version if provided.
# - assume running as $BUILD_USER user
install_custom_patches () {
	local version="$1"
	local dir

	if [ -d /data/config/$version ]; then
		log "- applying custom patches for $version"
		for dir in SPECS SOURCES; do
			if [ $(find /data/config/$version/$dir -type f | wc -l) != 0 ]; then
				copy_files /data/config/$version/$dir ~/rpmbuild/$dir
			fi
		done
		# applying patches if present to spec file
		# - applied in filesort order
		if [ $(find ~/rpmbuild/SPECS -type f -name "*patch*" | wc -l) != 0 ]; then
			for file in ~/rpmbuild/SPECS/*patch*; do
				log "- applying patch: $file"
				( cd ~/rpmbuild/SPECS && patch -p0 < $file )
			done
		fi

	else
		log "- No custom patches to apply for $version"
	fi
}

# return the src rpm location based on the build version / OS we are building
get_srpm_location () {
	location=$(grep ^$mysql_build_version $config | grep -w ${ID}.${BUILD_VERSION} | awk '{ print $5 }')

	echo $location
}

# build package
# - FIXME (add signing)
rpmbuild_rpms () {
	local label=${ID}.${VERSION_ID}__${mysql_build_version}__$(date +%Y%m%d.%H%M%S)

	cd ~/rpmbuild/SPECS
	# Careful with spacing and quoting!
	log "### rpmbuild started at $(date)"
	set -x
	rpmbuild --define 'el'$BUILD_VERSION' 1' -ba mysql.spec
	rc=$?
	set +x
	log "### rpmbuild terminated at $(date), exit status: $rc"

	# If build is successful record the installed package list,
	# or record the failed list as that may need fixing.
	rpm_qa=/data/log/rpm-qa.$label
	if [ $rc = 0 ]; then
		rpm -qa | sort > $rpm_qa
	else
		rpm -qa | sort > $rpm_qa.failed
	fi

	return $rc
}


# run the BUILD_USER stage: build rpms as the build user.
build_rpm_stage () {
	set -o pipefail
	local logfile=/data/log/build__${label}.log

	log "Sending build logging to $logfile"
	build_rpm_stage_logged 2>&1 | tee -a $logfile
}

# run the BUILD_USER stage with logging enabled
build_rpm_stage_logged () {
	log "### Starting build stage at $(date)"

	build_script=$(grep -w ${ID}.${BUILD_VERSION} $config | grep "^${mysql_build_version}[[:space:]]" | awk '{ print $4 }')

	if [ -z "$build_script" ]; then
		exit_error "No rpm build script defined for ${ID}.${BUILD_VERSION} and ${mysql_build_version}. Please configure one."
	fi

	build_script=/data/config/$build_script
	if [ ! -e "$build_script" ]; then
		log "Missing build script in $build_script to build $mysql_build_version on $ID.${BUILD_VERSION}"
		log "BUILD_VERSION: $BUILD_VERSION"
		log "NAME: $NAME"
		log "ID: $ID"
		log "VERSION_ID: $VERSION_ID"
		log "mysql_build_version: $mysql_build_version"
		exit 1
	fi

	log "Sourcing: $build_script"
	. $build_script
	log "Sourcing: $build_script complete"
	build

	rc=$?
	if [ $rc = 0 ]; then
		# Move built rpms to built location to ensure that they are kept
		log "### Build succeeded, moving rpms to /data/built"
		final_location=/data/built/${ID}.${BUILD_VERSION}__${mysql_build_version}
		if [ ! -d $final_location ]; then
			log "- creating directory $final_location"
			mkdir -p $final_location
		fi
		for file in ~/rpmbuild/SRPMS/*.rpm ~/rpmbuild/RPMS/*/*.rpm; do
			log "- moving $file --> $final_location"
			mv $file $final_location/
		done
		cp /etc/os-release $final_location/etc_os-release
	fi

	log "### Completed build stage at $(date) in $SECONDS seconds with exit status: $rc"
}

# run the root user stage: prepare the OS for the build
ossetup_stage () {
	local logfile=/data/log/ossetup__${label}.log

	log "Sending prepare logging to $logfile"
	set -o pipefail
	ossetup_stage_logged 2>&1 | tee -a $logfile
	log "ossetup_stage_logged took $SECONDS seconds to run" | tee -a $logfile

	# Complete the rpm build part if requested.
	# - if not indicate how to proceed
	if [ -z "$build_all" ]; then
		log "Continue the build as $BUILD_USER by doing:"
		log
		log "    su - $BUILD_USER /data/build $mysql_build_version"
		log
		log "Alternatively rerun the complete process in one go with:"
		log
		log "    $0 -a $mysql_build_version"
		log
		exit 0
	fi

	log "##############################################################"
	log "#  Switching to user $BUILD_USER to complete the rpm build"
	log "##############################################################"
	echo
	su - $BUILD_USER $0 $mysql_build_version
}

ossetup_stage_logged () {
	ossetup_script=$(grep -w ${ID}.${BUILD_VERSION} $config | grep "^${mysql_build_version}[[:space:]]" | awk '{ print $3 }')
	if [ -z "$ossetup_script" ]; then
		exit_error "No OS prepare script defined for ${ID}.${BUILD_VERSION} and ${mysql_build_version}. Please configure one."
	fi

	ossetup_script=/data/config/$ossetup_script
	if [ ! -e "$ossetup_script" ]; then
		log "Missing prepare script $location to prepare operating system $NAME ($ID $VERSION_ID) to build MySQL version $mysql_build_version"
		log "BUILD_VERSION: $BUILD_VERSION"
		log "NAME: $NAME"
		log "ID: $ID"
		log "VERSION_ID: $VERSION_ID"
		log "mysql_build_version: $mysql_build_version"
		exit 1
	fi

	log "########################################################"
	log "#    Preparing OS: $NAME ($ID $VERSION_ID)"
	log "#    for building rpms with label $mysql_build_version"
	log "########################################################"
	echo
	log "Sourcing: $ossetup_script"
	. $ossetup_script
	log "Sourcing: $ossetup_script complete"

	prepare
	setup_build_user

	log
	log "########################################################"
	log "#    Completed OS: $NAME ($ID $VERSION_ID) preparation"
	log "#    for building rpms with label $mysql_build_version"
	log "########################################################"
	echo
}

config=/data/build.conf
BUILD_USER=rpmbuild
build_all=

set -e

if [ -z "$USER" ]; then
	USER=$(id -un)
fi

while getopts an flag; do
	case $flag in
	a)	build_all=1 ;;
	n)	build_all= ;;
	*)	exit_error "INVALID FLAG $flag"
	esac
done
shift $(($OPTIND - 1))

mysql_build_version=$1
if [ -z "$mysql_build_version" ]; then
	exit_error "Please provide mysql_build_version name"
fi

get_os_and_version
# Used for logging
label=${mysql_build_version}__${ID}.${VERSION_ID}__$(date +%Y%m%d.%H%M%S)

case "$USER" in
root)		ossetup_stage;;
$BUILD_USER)	build_rpm_stage;;
*)		exit_error "unexpected USER $USER, please call the script properly"
esac
